name: Build and Deploy Docs

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with: 
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      
    - name: Build documentation
      run: sphinx-build ./jupyter docs

    - name: Commit documentation
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f docs/
        git commit -m "Update documentation" || true
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        key: ${{ secrets.DEPLOY_KEY }}
        branch: gh-pages